### ISSUE TITLE
inconsistent package with igibson 

### ISSUE THREAD

**Issue by jing-bi** [StanfordVL/behavior#1]
Thanks for the awesome package and looking forward to using it in my project.

However, seems some of the package imported in the BEHAVIOR code is not consistent with igibson main repo.

For example:

1. in `behavior_imitation_replay.py`, `from igibson.activity.activity_base import iGBEHAVIORActivityInstance`, but in the igibson main repo, this subpackage does not exist: https://github.com/StanfordVL/iGibson/tree/master/igibson
2. in `behavior_env_metrics.py`, `from igibson.envs.behavior_mp_env import BehaviorEnv`, in igibson repo under envs pkg, there is no `behavior_env` here: https://github.com/StanfordVL/iGibson/tree/master/igibson/envs

Please let me know how to fix these import problem, thanks

**Comment by ChengshuLi** [comment]
Hi, `behavior_env` has been deprecated. We will clean up the outdated reference in the next release. Sorry for the trouble!
